version: '3'

services:
  redis:
    image: "redis:alpine"
    restart: unless-stopped
  api:
    image: radiocontrol_api
    command: /srv/manage.py runserver 0.0.0.0:80
    environment:
        - RADIO_MPD_SERVER=172.18.0.1
    volumes:
        - /var/lib/mpd_test:/var/lib/mpd
        - /var/lib/mpd_test/db.sqlite3:/srv/db.sqlite3
    ports:
      - "80:80"
    hostname: radiocontrol
    depends_on:
      - redis
    restart: unless-stopped
  celery:
    image: radiocontrol_api
    command: celery -A radiocontrol_api worker -l info
    environment:
        - RADIO_MPD_SERVER=172.18.0.1
    depends_on:
      - redis
    restart: unless-stopped
